export const carDataConstants = {
    GET_CAR_DATA_REQUEST:'GET_CAR_DATA_REQUEST',
    GET_CAR_DATA_SUCCESS:'GET_CAR_DATA_SUCCESS',
    GET_CAR_DATA_FAILURE:'GET_CAR_DATA_FAILURE',
    UPDATE_CAR_DATA_FAILURE:'UPDATE_CAR_DATA_FAILURE'
}